### ISSUE TITLE
check version firmware

### ISSUE THREAD

**Issue by Seyyed1404** [otadrive/ESP32-OTAdrive-Examples#4]
Hi guy 
in 07-SSL example for arduino ide, do you have a check for version firmware?

**Comment by mostafahk** [comment]
Yes, there was a mistake on line `if(tick(0)....` line. We've corrected it.

**Comment by Seyyed1404** [comment]
i can not find this line if(tick(0)... in code

**Comment by Seyyed1404** [comment]
esp idf code for ([01-Simple FOTA]) is not in directory. do you have it?

i want this example for esp idf .

thank you
